# yugen palette — keep in sync with kitty/yugen.conf

foreground = #DEDEDE
background = #000000

palette = 0=#151515
palette = 1=#F57A7A
palette = 2=#8FBC9C
palette = 3=#FFF2AF
palette = 4=#8C9EB5
palette = 5=#FFBE89
palette = 6=#5FAFAF
palette = 7=#DEDEDE
palette = 8=#808080
palette = 9=#F9A0A0
palette = 10=#A3C4AE
palette = 11=#FFF2C8
palette = 12=#ADBCD0
palette = 13=#FFD4AC
palette = 14=#87C8C8
palette = 15=#FAFAFA

cursor-color = #A9A9A9
cursor-text = #000000

selection-background = #303030
selection-foreground = #FAFAFA

cursor-style = block
