foreground #D4D4D4
background #000000

# black
color0 #151515
color8 #505050

# red
color1 #F57A7A
color9 #F57A7A

# green
color2 #7EAB8E
color10 #7EAB8E

# yellow
color3  #FFF2AF
color11 #FFF2AF

# blue
color4  #A9A9A9
color12 #D4D4D4

# magenta
color5  #FFBE89
color13 #FFBE89

# cyan
color6  #696969
color14 #A9A9A9

# white
color7  #D4D4D4
color15 #FAFAFA

cursor #696969
cursor_text_color #000000

# Selection highlight
selection_background #303030
selection_foreground #FAFAFA

url_color #FFBE89

# Window borders
active_border_color #303030
inactive_border_color #151515
bell_border_color #FFBE89

# Title bar
macos_titlebar_color #000000
