# Everforest light (medium). Overrides every key yugen.conf sets.
foreground = #5C6A72
background = #FDF6E3

# black
palette = 0=#5C6A72
palette = 8=#829181

# red
palette = 1=#F85552
palette = 9=#E66868

# green
palette = 2=#8DA101
palette = 10=#93B259

# yellow
palette = 3=#DFA000
palette = 11=#DFA000

# blue
palette = 4=#3A94C5
palette = 12=#3A94C5

# magenta
palette = 5=#DF69BA
palette = 13=#DF69BA

# cyan
palette = 6=#35A77C
palette = 14=#35A77C

# white
palette = 7=#BDC3AF
palette = 15=#F4F0D9

cursor-color = #5C6A72
cursor-text = #FDF6E3

selection-background = #EAEDC8
selection-foreground = #5C6A72
