foreground = #DEDEDE
background = #000000

# black
palette = 0=#151515
palette = 8=#808080

# red
palette = 1=#F57A7A
palette = 9=#F9A0A0

# green
palette = 2=#8FBC9C
palette = 10=#A3C4AE

# yellow
palette = 3=#FFF2AF
palette = 11=#FFF2C8

# blue
palette = 4=#8C9EB5
palette = 12=#ADBCD0

# magenta
palette = 5=#FFBE89
palette = 13=#FFD4AC

# cyan
palette = 6=#5FAFAF
palette = 14=#87C8C8

# white
palette = 7=#DEDEDE
palette = 15=#FAFAFA

cursor-color = #A9A9A9
cursor-text = #000000

selection-background = #303030
selection-foreground = #FAFAFA
